Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.network "private_network", ip: "192.168.40.11"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = 2
    end
    web.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install apache2 wget unzip -y
      systemctl start apache2
      systemctl enable apache2
      cd /tmp/
      wget https://www.tooplate.com/zip-templates/2130_waso_strategy.zip
      unzip -o 2130_waso_strategy.zip
      cd 2130_waso_strategy && cp -r * /var/www/html/
      systemctl restart apache2
      SHELL
  end

  config.vm.define "db" do |db|
    db.vm.box = "geerlingguy/centos7"
    db.vm.network "private_network", ip: "192.168.40.12"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = 2
    end
    db.vm.provision "shell", inline: <<-SHELL
      yum install mariadb-server -y
      systemctl start mariadb
      systemctl enable mariadb
     
      sudo mysql -u root -e 'CREATE DATABASE wordpress;'
      sudo mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "admin123";'
      sudo mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
      sudo mysql -u root -e 'FLUSH PRIVILEGES;'
    SHELL
  end
end